spring.application.name=skillbridge-backend
spring.datasource.url=jdbc:postgresql://ep-hidden-silence-almsn2yt-pooler.c-3.eu-central-1.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_8vTBsuQY9MwR


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=${PORT:8080}